"""Pydantic request/response schemas.

Idea responses use the app's ``IdeaModel`` shape so the Kotlin side maps 1:1:
``{ id, category, title, description, tags }``.
"""
from typing import List, Optional

from pydantic import BaseModel, Field


# --- Responses ---------------------------------------------------------------

class IdeaModel(BaseModel):
    """Mirror of the Android `IdeaModel` data class."""

    id: str
    category: str = Field(..., description="Friendly content-type label, e.g. UNBOXING")
    title: str
    description: str
    tags: List[str] = Field(default_factory=list)


class EchoResponse(BaseModel):
    """Expanded-echo full text for one idea."""

    id: str
    full_text: str
    generated: bool = Field(
        ..., description="True if freshly generated by Gemini this call."
    )


class HealthResponse(BaseModel):
    status: str
    gemini_enabled: bool
    model: str
    user_id: str


class NicheInfo(BaseModel):
    id: str
    label: str
    description: str


class GenerateResponse(BaseModel):
    niche: str
    requested: int
    generated: int
    deduped: int
    ideas: List[IdeaModel]


class SwipeResponse(BaseModel):
    id: str
    action: str
    status: str
    saved: bool


# --- Requests ----------------------------------------------------------------

class SwipeRequest(BaseModel):
    action: str = Field(..., description="approve | reject | save")


class GenerateRequest(BaseModel):
    niche: str = Field(..., description="tech_reviews | gaming | fashion")
    count: int = Field(5, ge=1, le=20)


class TagsUpdateRequest(BaseModel):
    tags: List[str] = Field(default_factory=list)


class SettingsModel(BaseModel):
    push_notifications: bool = True
    daily_reminder: bool = True
    reduced_motion: bool = False
    notion_connected: bool = False
    calendar_connected: bool = False


class ProfileResponse(BaseModel):
    user_id: str
    display_name: str = "Editor"
    niche_id: Optional[str] = None
    goal_id: Optional[str] = None
    onboarded: bool = False
    settings: SettingsModel = Field(default_factory=SettingsModel)


class ProfileUpdateRequest(BaseModel):
    display_name: Optional[str] = None
    niche_id: Optional[str] = None
    goal_id: Optional[str] = None
    onboarded: Optional[bool] = None
